import { QRCodeSVG } from 'qrcode.react'
import { useParams } from 'react-router-dom'
import { useLiveDynamic } from '@/hooks/useLiveDynamic'
import { useLiveBracket } from '@/hooks/useLiveBracket'

function Header() {
  return <header className="relative z-20 flex shrink-0 items-center justify-between border-b border-white/10 pb-[clamp(8px,1.25vh,16px)]"><div className="font-display text-[clamp(1.35rem,2vw,2.35rem)] font-extrabold tracking-[-.045em]"><span className="text-[#a7d52c]">Rota de </span><span>Inovação</span></div><div className="flex items-center gap-4"><img src="/brand/energisa.png" alt="Grupo Energisa" className="h-[clamp(28px,4.4vh,44px)] w-auto"/><div className="h-9 w-px bg-white/30"/><img src="/brand/enova.png" alt="Enova" className="h-[clamp(25px,4vh,40px)] w-auto"/></div><div className="absolute -bottom-px left-0 h-px w-[42%] bg-gradient-to-r from-[#a7d52c] via-[#6bd27f] to-[#00b6da]"/></header>
}

function Ring({ seconds, total = 20 }: { seconds:number; total?:number }) {
  const radius=82,c=2*Math.PI*radius,p=Math.max(0,Math.min(1,seconds/Math.max(1,total)))
  return <div className="relative grid aspect-square w-[min(19vw,24vh)] place-items-center"><svg viewBox="0 0 200 200" className="absolute inset-0 h-full w-full -rotate-90"><circle cx="100" cy="100" r={radius} fill="none" stroke="rgba(255,255,255,.08)" strokeWidth="10"/><circle cx="100" cy="100" r={radius} fill="none" stroke="#a7d52c" strokeWidth="10" strokeLinecap="round" strokeDasharray={c} strokeDashoffset={c*(1-p)} style={{filter:'drop-shadow(0 0 8px rgba(167,213,44,.45))'}}/><circle cx="100" cy="100" r="94" fill="none" stroke="rgba(0,182,218,.28)" strokeWidth="1" strokeDasharray="2 8"/></svg><div className="font-display text-[clamp(3.2rem,6vw,5.7rem)] font-extrabold leading-none text-[#a7d52c]">{String(Math.max(0,seconds)).padStart(2,'0')}</div></div>
}

function Waves(){return <svg className="pointer-events-none absolute inset-x-0 bottom-0 h-[26%] w-full opacity-55" viewBox="0 0 1600 330" preserveAspectRatio="none"><defs><pattern id="lc" width="17" height="17" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1.45" fill="#00b6da"/></pattern><pattern id="ll" width="17" height="17" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1.45" fill="#a7d52c"/></pattern></defs><path d="M-40 275 C190 105 365 335 660 218 C920 115 1090 32 1650 128 L1650 350 L-40 350 Z" fill="url(#lc)" opacity=".72"/><path d="M-20 302 C190 175 395 327 680 260 C900 208 1010 142 1240 200 C1395 240 1505 224 1640 183" fill="none" stroke="url(#ll)" strokeWidth="34" strokeDasharray="2 14" opacity=".75"/></svg>}

function Pair({label,players,winnerId}:{label:string;players:any[];winnerId?:string|null}){
  return <div className="rounded-[24px] border border-white/11 bg-[#071936]/80 p-[clamp(14px,2vw,24px)]"><div className="text-xs font-bold uppercase tracking-[.18em] text-[#00b6da]">{label}</div><div className="mt-4 space-y-3">{players.map((p:any)=><div key={p.id} className={`grid grid-cols-[minmax(0,1fr)_auto] items-center gap-5 rounded-[18px] border px-5 py-4 ${winnerId===p.id?'border-[#a7d52c]/35 bg-[#a7d52c]/10':'border-white/8 bg-white/[.035]'}`}><div className="truncate font-display text-[clamp(1.2rem,2vw,2.1rem)] font-extrabold">{winnerId===p.id?'🏆 ':''}{p.display_name}</div><div className="text-right"><div className="font-display text-[clamp(1.5rem,2.5vw,2.7rem)] font-extrabold text-[#bfe84a]">{Number(p.total_score??0).toLocaleString('pt-BR')}</div><div className="text-xs text-white/42">{Number(p.correct_count??0)} acertos</div></div></div>)}</div></div>
}

function Options({question}:{question:any}){
  const options=Array.isArray(question?.options)?question.options:[]
  return <div className="mt-7 grid grid-cols-2 gap-4">{options.map((option:any,index:number)=><div key={option.optionId??index} className={`rounded-[22px] border px-5 py-4 ${option.isCorrect?'border-[#a7d52c]/45 bg-[#a7d52c]/10':'border-white/10 bg-white/[.045]'}`}><div className={`mb-2 inline-flex h-9 w-9 items-center justify-center rounded-full font-display font-bold ${option.isCorrect?'bg-[#a7d52c]/16 text-[#c4eb50]':'bg-[#00b6da]/10 text-[#55d7ef]'}`}>{String.fromCharCode(65+index)}</div><div className="text-[clamp(.95rem,1.18vw,1.3rem)] font-medium text-white/86">{option.text}</div></div>)}</div>
}

export function ScreenLiveVisualPage(){
  const {sessionId}=useParams<{sessionId:string}>()
  const {session,connected,question,ranking,remainingSeconds,currentRound}=useLiveDynamic(sessionId)
  const bracket=useLiveBracket(session)
  const flow=String(session?.paused?'paused':session?.flow_state??'lobby')
  const joinUrl=session?`${window.location.origin}/quiz/entrar/${session.code}`:''
  const top4=ranking.slice(0,4)
  const semiWinner1=bracket.semifinal1.players.find((p:any)=>p.id===bracket.semifinal1.match?.winner_player_id)
  const semiWinner2=bracket.semifinal2.players.find((p:any)=>p.id===bracket.semifinal2.match?.winner_player_id)
  const champion=bracket.final.players.find((p:any)=>p.id===bracket.final.match?.winner_player_id)
  const quizCorrect=question?.options.find((o:any)=>o.isCorrect)
  const bracketCorrect=bracket.question?.options.find((o:any)=>o.isCorrect)
  const quizTotal=Number(currentRound?.timer_duration_seconds??session?.question_time_seconds??20)
  const semiTotal=Number(bracket.semifinal1.round?.timer_duration_seconds??session?.question_time_seconds??20)
  const finalTotal=Number(bracket.final.round?.timer_duration_seconds??session?.question_time_seconds??20)

  let content:React.ReactNode
  if(!session) content=<div className="grid min-h-0 flex-1 place-items-center text-white/60">Carregando…</div>
  else if(flow==='lobby') content=<section className="grid min-h-0 flex-1 grid-cols-[minmax(0,1.25fr)_minmax(280px,.75fr)] items-center gap-12"><div><div className="inline-flex rounded-full border border-[#a7d52c]/25 bg-[#a7d52c]/8 px-4 py-1.5 text-xs font-bold uppercase tracking-[.15em] text-[#c2e94a]">Aguardando participantes</div><h1 className="mt-6 font-display text-[clamp(3rem,6.4vw,7rem)] font-extrabold leading-[.92] tracking-[-.06em]">O jogo vai<br/><span className="text-[#a7d52c]">começar!</span></h1><p className="mt-5 text-[clamp(1rem,1.6vw,1.7rem)] text-white/68">Entre pelo celular e prepare-se para a Rota de Inovação.</p><div className="mt-7 flex items-center gap-4"><div className="font-display text-[clamp(2rem,4vw,4.2rem)] font-extrabold text-[#a7d52c]">{connected.length}</div><div className="text-white/70">participantes<br/><span className="font-semibold text-white">conectados</span></div></div></div><div className="justify-self-center rounded-[28px] border border-white/12 bg-white/[.055] p-6"><div className="rounded-2xl bg-white p-4"><QRCodeSVG value={joinUrl} size={220} fgColor="#07152f" bgColor="#fff"/></div><div className="mt-4 text-center font-semibold text-white/75">Aponte a câmera e participe</div></div></section>
  else if(flow==='prepare') content=<section className="grid min-h-0 flex-1 place-items-center text-center"><div><div className="text-[clamp(1rem,1.8vw,2rem)] font-semibold uppercase tracking-[.28em] text-white/55">Prepare-se</div><div className="mt-5"><Ring seconds={remainingSeconds} total={Number(session.prepare_seconds??3)}/></div></div></section>
  else if(flow==='question') content=<section className="grid min-h-0 flex-1 grid-cols-[minmax(0,1fr)_minmax(220px,24vh)] items-center gap-7"><div><div className="text-sm font-bold uppercase tracking-[.2em] text-[#00b6da]">Quiz coletivo</div><div className="mt-2 font-display text-2xl font-bold">Pergunta {session.current_question_number} <span className="text-white/45">de {session.questions_total}</span></div><h1 className="mt-5 max-w-[1100px] font-display text-[clamp(2rem,3.6vw,4.2rem)] font-extrabold leading-[1.02] tracking-[-.05em]">{question?.statement??'Preparando pergunta…'}</h1><Options question={question}/></div><div className="justify-self-center"><div className="mb-3 text-center text-xs font-semibold uppercase tracking-[.24em] text-[#00b6da]">Tempo restante</div><Ring seconds={remainingSeconds} total={quizTotal}/></div></section>
  else if(flow==='reveal') content=<section className="grid min-h-0 flex-1 place-items-center text-center"><div><div className="inline-flex rounded-full border border-[#00b6da]/25 bg-[#00b6da]/8 px-4 py-1.5 text-xs font-bold uppercase tracking-[.16em] text-[#55d7ef]">Resposta correta</div><div className="mt-6 font-display text-[clamp(3rem,8vw,7rem)] font-extrabold leading-[.9] text-[#a7d52c]">{quizCorrect?String.fromCharCode(65+(question?.options.findIndex((o:any)=>o.optionId===quizCorrect.optionId)??0)):'✓'}</div><div className="mt-3 font-display text-[clamp(2rem,4vw,4.3rem)] font-extrabold tracking-[-.05em]">{quizCorrect?.text??'Resposta revelada'}</div></div></section>
  else if(flow==='ranking') content=<section className="grid min-h-0 flex-1 place-items-center"><div className="w-full max-w-5xl rounded-[30px] border border-white/10 bg-[#071936]/62 p-6"><div className="mb-5 text-center font-display text-3xl font-extrabold">Ranking parcial</div><div className="space-y-2">{ranking.slice(0,5).map((item:any,index:number)=><div key={item.participant_id} className={`grid grid-cols-[58px_minmax(0,1fr)_auto] items-center gap-4 rounded-[18px] border px-5 py-3 ${index<4?'border-[#a7d52c]/20 bg-[#a7d52c]/8':'border-white/8 bg-white/[.03]'}`}><div className="font-display text-xl font-extrabold text-[#bfe84a]">{index+1}</div><div className="text-lg font-semibold">{item.display_name}</div><div className="font-display text-lg font-bold text-white/80">{Number(item.total_score??0).toLocaleString('pt-BR')}</div></div>)}</div></div></section>
  else if(flow==='paused') content=<section className="grid min-h-0 flex-1 place-items-center text-center"><div><div className="text-sm font-bold uppercase tracking-[.2em] text-[#ffb547]">Jogo pausado</div><h1 className="mt-5 font-display text-[clamp(3rem,6vw,6rem)] font-extrabold tracking-[-.06em]">Aguardando retomada</h1><p className="mt-4 text-xl text-white/60">A partida continuará exatamente deste ponto.</p></div></section>
  else if(flow==='quiz_result') content=<section className="grid min-h-0 flex-1 place-items-center"><div className="w-full max-w-5xl"><div className="text-center text-sm font-bold uppercase tracking-[.2em] text-[#00b6da]">Classificados</div><h1 className="mt-3 text-center font-display text-[clamp(2.8rem,5vw,5rem)] font-extrabold tracking-[-.055em]">Top 4 das Semifinais</h1><div className="mt-7 grid grid-cols-2 gap-4">{top4.map((item:any,index:number)=><div key={item.participant_id} className="flex items-center gap-5 rounded-[24px] border border-[#a7d52c]/22 bg-[#a7d52c]/8 px-6 py-5"><div className="font-display text-[clamp(2rem,4vw,4rem)] font-extrabold text-[#bfe84a]">{index+1}º</div><div><div className="font-display text-[clamp(1.25rem,2.2vw,2.3rem)] font-extrabold">{item.display_name}</div><div className="text-white/45">{Number(item.total_score??0).toLocaleString('pt-BR')} pontos</div></div></div>)}</div><div className="mt-5 text-center text-white/55">Chaveamento: 1º × 4º e 2º × 3º</div></div></section>
  else if(flow==='semifinal_prepare') content=<section className="grid min-h-0 flex-1 grid-cols-[minmax(0,1fr)_minmax(240px,25vh)] items-center gap-8"><div><div className="text-sm font-bold uppercase tracking-[.2em] text-[#00b6da]">Semifinais</div><h1 className="mt-3 font-display text-[clamp(2.8rem,5vw,5.3rem)] font-extrabold tracking-[-.055em]">Preparem-se!</h1><div className="mt-6 grid grid-cols-2 gap-4"><Pair label="1º × 4º" players={bracket.semifinal1.players}/><Pair label="2º × 3º" players={bracket.semifinal2.players}/></div></div><div className="justify-self-center"><Ring seconds={remainingSeconds} total={Number(session.prepare_seconds??3)}/></div></section>
  else if(flow==='semifinal_question') content=<section className="grid min-h-0 flex-1 grid-cols-[minmax(0,1fr)_minmax(320px,.55fr)] gap-6"><div className="flex min-h-0 flex-col justify-center"><div className="text-sm font-bold uppercase tracking-[.2em] text-[#00b6da]">Semifinais · Rodada {bracket.semifinal1.match?.current_round_number??1}</div><h1 className="mt-4 font-display text-[clamp(1.8rem,3vw,3.5rem)] font-extrabold leading-[1.04] tracking-[-.045em]">{bracket.question?.statement??'Preparando pergunta…'}</h1><Options question={bracket.question}/></div><div className="flex min-h-0 flex-col justify-center gap-3"><div className="mx-auto"><Ring seconds={remainingSeconds} total={semiTotal}/></div><Pair label="Semifinal 1" players={bracket.semifinal1.players}/><Pair label="Semifinal 2" players={bracket.semifinal2.players}/></div></section>
  else if(flow==='semifinal_reveal') content=<section className="grid min-h-0 flex-1 grid-cols-[minmax(0,1fr)_minmax(430px,.8fr)] items-center gap-8"><div className="text-center"><div className="text-xs font-bold uppercase tracking-[.2em] text-[#00b6da]">Resposta correta</div><div className="mt-5 font-display text-[clamp(3rem,7vw,7rem)] font-extrabold text-[#a7d52c]">{bracketCorrect?String.fromCharCode(65+(bracket.question?.options.findIndex((o:any)=>o.optionId===bracketCorrect.optionId)??0)):'✓'}</div><div className="mt-2 font-display text-[clamp(1.8rem,3vw,3.3rem)] font-extrabold">{bracketCorrect?.text??'Resposta revelada'}</div></div><div className="grid gap-3"><Pair label="Semifinal 1" players={bracket.semifinal1.players}/><Pair label="Semifinal 2" players={bracket.semifinal2.players}/></div></section>
  else if(flow==='semifinal_result') content=<section className="grid min-h-0 flex-1 place-items-center"><div className="w-full max-w-5xl text-center"><div className="text-sm font-bold uppercase tracking-[.2em] text-[#00b6da]">Semifinais concluídas</div><h1 className="mt-3 font-display text-[clamp(3rem,5.7vw,6rem)] font-extrabold tracking-[-.06em]">Temos os finalistas!</h1><div className="mt-8 grid grid-cols-2 gap-5">{[semiWinner1,semiWinner2].filter(Boolean).map((p:any)=><div key={p.id} className="rounded-[28px] border border-[#a7d52c]/28 bg-[#a7d52c]/9 p-7"><div className="text-xs font-bold uppercase tracking-[.16em] text-[#bfe84a]">Finalista</div><div className="mt-3 font-display text-[clamp(1.8rem,3.5vw,3.7rem)] font-extrabold">{p.display_name}</div></div>)}</div><p className="mt-6 text-xl text-white/55">Aguardando o apresentador iniciar a Grande Final.</p></div></section>
  else if(flow==='final_prepare') content=<section className="grid min-h-0 flex-1 grid-cols-[minmax(0,1fr)_minmax(240px,25vh)] items-center gap-8"><div><div className="text-sm font-bold uppercase tracking-[.2em] text-[#00b6da]">Grande Final</div><h1 className="mt-3 font-display text-[clamp(3rem,6vw,6rem)] font-extrabold tracking-[-.06em]">A decisão começa agora</h1><div className="mt-7 max-w-3xl"><Pair label="Final" players={bracket.final.players}/></div></div><div className="justify-self-center"><Ring seconds={remainingSeconds} total={Number(session.prepare_seconds??3)}/></div></section>
  else if(flow==='final_question') content=<section className="grid min-h-0 flex-1 grid-cols-[minmax(0,1fr)_minmax(330px,.55fr)] gap-7"><div className="flex min-h-0 flex-col justify-center"><div className="text-sm font-bold uppercase tracking-[.2em] text-[#00b6da]">Grande Final · Rodada {bracket.final.match?.current_round_number??1}</div><h1 className="mt-4 font-display text-[clamp(1.9rem,3.2vw,3.7rem)] font-extrabold leading-[1.04] tracking-[-.045em]">{bracket.question?.statement??'Preparando pergunta…'}</h1><Options question={bracket.question}/></div><div className="flex flex-col justify-center gap-5"><div className="mx-auto"><Ring seconds={remainingSeconds} total={finalTotal}/></div><Pair label="Placar" players={bracket.final.players}/></div></section>
  else if(flow==='final_reveal') content=<section className="grid min-h-0 flex-1 grid-cols-[minmax(0,1fr)_minmax(430px,.7fr)] items-center gap-8"><div className="text-center"><div className="text-xs font-bold uppercase tracking-[.2em] text-[#00b6da]">Resposta correta</div><div className="mt-5 font-display text-[clamp(3rem,7vw,7rem)] font-extrabold text-[#a7d52c]">{bracketCorrect?String.fromCharCode(65+(bracket.question?.options.findIndex((o:any)=>o.optionId===bracketCorrect.optionId)??0)):'✓'}</div><div className="mt-2 font-display text-[clamp(1.8rem,3vw,3.3rem)] font-extrabold">{bracketCorrect?.text??'Resposta revelada'}</div></div><Pair label="Grande Final" players={bracket.final.players}/></section>
  else if(flow==='champion') content=<section className="grid min-h-0 flex-1 place-items-center text-center"><div><div className="mx-auto grid h-28 w-28 place-items-center rounded-full border border-[#a7d52c]/30 bg-[#a7d52c]/10 text-6xl">🏆</div><div className="mt-6 text-sm font-bold uppercase tracking-[.26em] text-[#00b6da]">Campeão da Rota de Inovação</div><h1 className="mt-4 font-display text-[clamp(4rem,9vw,9rem)] font-extrabold leading-[.9] tracking-[-.07em] text-[#a7d52c]">{champion?.display_name??'Campeão'}</h1><p className="mt-6 text-[clamp(1.1rem,2vw,2rem)] text-white/62">Parabéns pela conquista!</p></div></section>
  else if(flow==='finished') content=<section className="grid min-h-0 flex-1 place-items-center text-center"><div><div className="text-sm font-bold uppercase tracking-[.2em] text-[#00b6da]">Dinâmica encerrada</div><h1 className="mt-5 font-display text-[clamp(3rem,6vw,6rem)] font-extrabold tracking-[-.06em]">Obrigado por participar!</h1></div></section>
  else content=<section className="grid min-h-0 flex-1 place-items-center text-center"><h1 className="font-display text-5xl font-extrabold">{flow}</h1></section>

  return <main className="relative h-[100dvh] overflow-hidden bg-[#020d23] text-white"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_18%_8%,rgba(23,77,145,.23),transparent_32%),radial-gradient(circle_at_83%_20%,rgba(0,182,218,.09),transparent_28%),linear-gradient(180deg,#03102b_0%,#020d23_100%)]"/><Waves/><div className="relative mx-auto grid h-full max-w-[1800px] grid-rows-[auto_minmax(0,1fr)] px-[clamp(14px,2.2vw,40px)] py-[clamp(12px,1.8vh,24px)]"><Header/>{content}</div></main>
}
